name: Push to Lambda in test environment
on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy to Lambda
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
